
# Custom
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: metric-app
      metric:
        name: metric_app_http_requests_total
      target:
        value: "1000"
        type: Value
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 30
        periodSeconds: 5
      - type: Pods
        value: 2
        periodSeconds: 5
      selectPolicy: Max