---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metric-app
  name: metric-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-app
  template:
    metadata:
      labels:
        app: metric-app
    spec:
      containers:
      - name: metric-app
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: metric-app
  labels:
    app: metric-app
spec:
  type: NodePort
  ports:
   - name: web
     port: 8080
     targetPort: web
     nodePort: 30500
     protocol: TCP
  selector:
   app: metric-app

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: metric-app
    release: kube-prometheus-stack
  name: metric-app-monitor
spec:
  endpoints:
    - targetPort: web
      path: /metrics
  selector:
    matchLabels:
      app: metric-app